dist: trusty
language: node_js
node_js:
    - "7"
    - "6"
    - "5"
python:
    - "3.6"
    - "3.5"
    - "3.4"
env:
    - os: linux
      addons:
          apt:
              sources:
                  - ubuntu-toolchain-r-test
              packages:
                  - g++-5
      env:
          - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
    - os: linux
      addons:
          apt:
              sources:
                  - ubuntu-toolchain-r-test
              packages:
                  - g++-6
      env:
          - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
before_install:
    - python3 --version
    - python3-config --cflags
    - python3-config --ldflags
    - export LD_LIBRARY_PATH=`python3-config --prefix`/lib
    - eval "${MATRIX_EVAL}"
