dist: trusty
language: node_js
node_js:
  - "7"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
env:
  - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
before_install:
  - eval "${MATRIX_EVAL}"
  - $CXX --version
  - node --version
  - python3 --version
  - python3-config --cflags
  - python3-config --ldflags
before_script:
  - ldd build/Release/obj.target/pyjs-native.node
