os:
    - linux
dist: trusty
language: node_js
node_js:
    - "7"
    - "6"
    - "5"
python:
    - "3.6"
    - "3.5"
    - "3.4"
env:
    - addons:
          apt:
              sources:
                  - ubuntu-toolchain-r-test
              packages:
                  - g++-5
    - addons:
          apt:
              sources:
                  - ubuntu-toolchain-r-test
              packages:
                  - g++-6
before_install:
    - $CXX --version
    - python3 --version
    - python3-config --cflags
    - python3-config --ldflags
